#!/bin/bash

# Author: Samuel Omlin, CSCS (omlins)
#
# Description: Definition of site specific variables and call of JUHPC.
# Site: LUMI, EuroHPC JU
# Base: craype (LUMI-flavored)

# Load required modules (including correct CPU and GPU target modules)
module load LUMI
module load partition/G         # loads CPU and GPU target modules (craype-x86-trento, craype-accel-amd-gfx90a)
module load cpeGNU              # LUMI-wrapper for PrgEnv-gnu
module load rocm
module load cray-hdf5-parallel
module list

# Environment variables for HPC key packages that require system libraries that require system libraries (MPI.jl, CUDA.jl, AMDGPU.jl, HDF5.jl and ADIOS2.jl)
export JUHPC_ROCM_HOME=$ROCM_PATH
export JUHPC_MPI_VENDOR="cray"
export JUHPC_MPI_EXEC="srun"
export JUHPC_HDF5_HOME=$HDF5_DIR


# Call JUHPC
JUHPC_SETUP_INSTALLDIR=$SCRATCH/${HOSTNAME%%[0-9]*}/juhpc_setup  #SCRATCH is assumed to be defined in ~/.bashrc, e.g., SCRATCH=/scratch/project_465000105/$USER
JULIAUP_INSTALLDIR="\$SCRATCH/\${HOSTNAME%%[0-9]*}/juliaup"
VERSION="v0.4.0"
wget https://raw.githubusercontent.com/JuliaParallel/JUHPC/$VERSION/juhpc -O ./juhpc
bash -l ./juhpc $JUHPC_SETUP_INSTALLDIR $JULIAUP_INSTALLDIR --verbose=1
