#!/bin/bash

# Author: Samuel Omlin, CSCS (omlins)
#
# Description: Definition of site specific variables and call of JUHPC.
# Site: Piz Daint:mc, Swiss National Supercomputing Centre (CSCS)
# Base: craype


# Load required modules, including correct CPU and GPU target modules (NOTE: the same modules should be loaded when running julia - JUHPC can be used in a module build recipe...)
module load daint-mc
module switch PrgEnv-cray PrgEnv-gnu
module load cray-hdf5-parallel
module list


# Environment variables for HPC key packages that require system libraries that require system libraries (MPI.jl, CUDA.jl, HDF5.jl and ADIOS2.jl)
export JUHPC_MPI_HOME=$MPICH_DIR
export JUHPC_MPI_EXEC="srun -C mc"
export JUHPC_HDF5_HOME=$HDF5_DIR


# Call JUHPC
git clone https://github.com/omlins/JUHPC
JUHPC=./JUHPC/src/juhpc
JUHPC_SETUP_INSTALLDIR=$SCRATCH/../julia/${HOSTNAME%%[0-9]*}-mc/juhpc_setup
JULIAUP_INSTALLDIR="\$SCRATCH/../julia/\$USER/\${HOSTNAME%%[0-9]*}-mc/juliaup"
bash -l $JUHPC $JUHPC_SETUP_INSTALLDIR $JULIAUP_INSTALLDIR
